### ISSUE TITLE
Cannot set profile timeout

### ISSUE THREAD

**Issue by PR-O** [pac4j/play-pac4j-java-demo#27]
The commented line in SecurityModule.java meant to set the profile timeout does not seem to work. This is the relevant line:

    // for test purposes: profile timeout = 60 seconds
    ((PlayCacheStore) config.getSessionStore()).setProfileTimeout(60);

This yields an error on initializing the module:

    Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

	1) An exception was caught and reported. Message: null
	  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)

	1 error
		at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466) ~[guice-4.0.jar:na]
		at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[guice-4.0.jar:na]
		at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.0.jar:na]
		at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0.jar:na]
		at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.0.jar:na]
		at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.0.jar:na]
		at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126) ~[play_2.11-2.4.0.jar:2.4.0]
		at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93) ~[play_2.11-2.4.0.jar:2.4.0]
		at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21) ~[play_2.11-2.4.0.jar:2.4.0]
		at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153) ~[play-server_2.11-2.4.0.jar:2.4.0]
		at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150) ~[play-server_2.11-2.4.0.jar:2.4.0]
		at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.0.jar:2.4.0]
		at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150) ~[play-server_2.11-2.4.0.jar:2.4.0]
		... 14 common frames omitted
	Caused by: java.lang.NullPointerException: null
		at modules.SecurityModule.configure(SecurityModule.java:100) ~[na:na]
		at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
		at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
		at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
		at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177) ~[guice-4.0.jar:na]
		at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
		at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
		at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
		at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.0.jar:na]
		at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0.jar:na]
		... 24 common frames omitted

How can I set the profile timeout?

**Comment by leleuj** [comment]
You're right. By default, the `sessionStore` is null. The appropriate source code is to create a `PlayCacheStore`, set the timeout and set it to the `sessionStore`.

Would you mind pushing a PR for that? Thanks

**Comment by PR-O** [comment]
Not at all.

**Comment by PR-O** [comment]
#28
