### ISSUE TITLE
Internal error with JWT & Google login

### ISSUE THREAD

**Issue by eximius313** [pac4j/play-pac4j-java-demo#53]
1) I run demo app
2) successfully logged with Google account
3) entered JWT page (http://localhost:9000/jwt.html)
4) got:
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[TechnicalException: profile.sub must be null]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:204)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:164)
        at play.core.j.JavaHttpErrorHandlerAdapter.$anonfun$onServerError$1(JavaHttpErrorHandlerAdapter.scala:22)
        at play.core.j.JavaHelpers.$anonfun$invokeWithContext$1(JavaHelpers.scala:273)
        at play.core.j.JavaHelpers.withContext(JavaHelpers.scala:284)
        at play.core.j.JavaHelpers.withContext$(JavaHelpers.scala:280)
        at play.core.j.JavaHelpers$.withContext(JavaHelpers.scala:293)
        at play.core.j.JavaHelpers.invokeWithContext(JavaHelpers.scala:272)
        at play.core.j.JavaHelpers.invokeWithContext$(JavaHelpers.scala:271)
        at play.core.j.JavaHelpers$.invokeWithContext(JavaHelpers.scala:293)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:22)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:363)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:361)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.pac4j.core.exception.TechnicalException: profile.sub must be null
        at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:109)
        at org.pac4j.core.util.CommonHelper.assertNull(CommonHelper.java:151)
        at org.pac4j.jwt.profile.JwtGenerator.verifyProfile(JwtGenerator.java:104)
        at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:74)
        at controllers.Application.jwt(Application.java:161)
        at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$30(Routes.scala:683)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:88)
        at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:138)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
        at scala.concurrent.impl.Promise.transform(Promise.scala:29)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
        at scala.concurrent.Future.map(Future.scala:289)
        at scala.concurrent.Future.map$(Future.scala:289)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
        at scala.concurrent.Future$.apply(Future.scala:655)
        at play.core.j.JavaAction.apply(JavaAction.scala:138)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
        at play.api.libs.streams.FlattenedAccumulator.$anonfun$run$2(Accumulator.scala:231)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        ... 13 common frames omitted
```

This is thrown in both JDK8 & JDK9

**Comment by leleuj** [comment]
This issue occurs in the pac4j project, not in the play-pac4j one.

It's a check to ensure the profile has no `sub` attribute, as one will be created at the generation time. We could maybe remove this check and only raise a warning in the log.

**Comment by eximius313** [comment]
It's up to you. I was just playing around with Demo and this surprised me

**Comment by leleuj** [comment]
I will think about it.

**Comment by eximius313** [comment]
@leleuj - what was the solution?

**Comment by leleuj** [comment]
I kept the current behavior as there was no other complain.

**Comment by eximius313** [comment]
How many people could test the demo app? The exception is there and the bug is there. It is reproducible as well.

**Comment by leleuj** [comment]
OK. It's fixed in this commit: https://github.com/pac4j/pac4j/commit/17bfa1b216244b012bd60afec0e78ad165885b10
