### ISSUE TITLE
Upgrade to newest Deadbolt thows Error

### ISSUE THREAD

**Issue by eximius313** [pac4j/play-pac4j-java-demo#54]
I've tried to upgrade to deadbolt `2.6.4` but when I run the app and navigate to http://localhost:9000/form/index.html I get:
```
Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-2]: Method org/pac4j/play/deadbolt2/Pac4jHandler.beforeAuthCheck(Lplay/mvc/Http$Context;Ljava/util/Optional;)Ljava/util/concurrent/CompletionStage; is abstract, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play-dev-mode]
java.lang.AbstractMethodError: Method org/pac4j/play/deadbolt2/Pac4jHandler.beforeAuthCheck(Lplay/mvc/Http$Context;Ljava/util/Optional;)Ljava/util/concurrent/CompletionStage; is abstract
        at org.pac4j.play.deadbolt2.Pac4jHandler.beforeAuthCheck(Pac4jHandler.java)
        at be.objectify.deadbolt.java.cache.DefaultBeforeAuthCheckCache.apply(DefaultBeforeAuthCheckCache.java:78)
        at be.objectify.deadbolt.java.cache.DefaultBeforeAuthCheckCache.apply(DefaultBeforeAuthCheckCache.java:35)
        at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.preAuth(AbstractDeadboltAction.java:286)
        at be.objectify.deadbolt.java.actions.AbstractSubjectAction.execute(AbstractSubjectAction.java:55)
        at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:141)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:138)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
        at scala.concurrent.impl.Promise.transform(Promise.scala:29)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
        at scala.concurrent.Future.map(Future.scala:289)
        at scala.concurrent.Future.map$(Future.scala:289)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
        at scala.concurrent.Future$.apply(Future.scala:655)
        at play.core.j.JavaAction.apply(JavaAction.scala:138)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
        at play.api.libs.streams.FlattenedAccumulator.$anonfun$run$2(Accumulator.scala:231)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] - akka.actor.ActorSystemImpl - Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-2]: Method org/pac4j/play/deadbolt2/Pac4jHandler.beforeAuthCheck(Lplay/mvc/Http$Context;Ljava/util/Optional;)Ljava/util/concurrent/CompletionStage; is abstract, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play-dev-mode]
java.lang.AbstractMethodError: Method org/pac4j/play/deadbolt2/Pac4jHandler.beforeAuthCheck(Lplay/mvc/Http$Context;Ljava/util/Optional;)Ljava/util/concurrent/CompletionStage; is abstract
        at org.pac4j.play.deadbolt2.Pac4jHandler.beforeAuthCheck(Pac4jHandler.java)
        at be.objectify.deadbolt.java.cache.DefaultBeforeAuthCheckCache.apply(DefaultBeforeAuthCheckCache.java:78)
        at be.objectify.deadbolt.java.cache.DefaultBeforeAuthCheckCache.apply(DefaultBeforeAuthCheckCache.java:35)
        at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.preAuth(AbstractDeadboltAction.java:286)
        at be.objectify.deadbolt.java.actions.AbstractSubjectAction.execute(AbstractSubjectAction.java:55)
        at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:141)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:138)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
        at scala.concurrent.impl.Promise.transform(Promise.scala:29)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
        at scala.concurrent.Future.map(Future.scala:289)
        at scala.concurrent.Future.map$(Future.scala:289)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
        at scala.concurrent.Future$.apply(Future.scala:655)
        at play.core.j.JavaAction.apply(JavaAction.scala:138)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
        at play.api.libs.streams.FlattenedAccumulator.$anonfun$run$2(Accumulator.scala:231)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[INFO] [07/23/2018 18:58:16.123] [Thread-2] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

**Comment by leleuj** [comment]
play-pac4j v6.1.0 is currently based on Deadbolt v2.6.0, so there is certainly a breaking change. Have you tried upgrading play-pac4j v6.1.0 to Deadbolt v2.6.4? Thanks

**Comment by eximius313** [comment]
Shall I upgrade Demo to `play-pac4j v6.1.0` as well?

**Comment by leleuj** [comment]
The version 6.1.0 has not been released yet, so you must use the `6.1.0-SNAPSHOT` version... Please update the version of the demos also (I created a 6.0.x branch).

**Comment by leleuj** [comment]
I upgraded the demos so you can just focus on the Deadbolt version upgrade...

**Comment by petahathub** [comment]
Hi,

how are things about deadbolt 2.6.4?

**Comment by leleuj** [comment]
It has not been done yet. Feel free to give it a try.

**Comment by leleuj** [comment]
play-pac4j v9 (Play v2.7, pac4j v4) has been upgraded to Deadbolt 2 v2.7.1.
